Reviewed up to revision 458
git-svn-id: http://overlays.gentoo.org/svn/proj/sunrise@459 12608f7e-a915-0410-b2f3-ce240db1b126

diff --git a/reviewed/scripts/sunrise-commit b/reviewed/scripts/sunrise-commit
--- a/reviewed/scripts/sunrise-commit
+++ b/reviewed/scripts/sunrise-commit
@@ -1,7 +1,6 @@
 #!/bin/bash
 # sunrise-commit - Automates the Gentoo Sunrise Overlay commit process
 # Released into the public domain
-# $Id$
 
 source /sbin/functions.sh
 
@@ -26,6 +25,14 @@ opt_verbose=0
 
 changelog_append() {
 	if [[ "$opt_changelog" == "1" ]] ; then
+		if [[ "$(svn status)" =~ 'ChangeLog' ]] ; then
+			echo "!!! Error: Only one ChangeLog entry should be made per commit, and you have"
+			echo "!!! already modified your ChangeLog locally since your last commit. To keep the"
+			echo "!!! pre-existing modifications please run sunrise-commit again without the -c"
+			echo "!!! option. To discard the pre-existing modifications run:"
+			echo "!!!   svn revert ChangeLog"
+			exit 1
+		fi
 		ebegin "Appending/creating ChangeLog"
 		echangelog "$*"
 		eend $?
@@ -42,10 +49,10 @@ create_digests() {
 	fi
 }
 
+
 repoman_check() {
 	if [[ "$opt_norepoman" == "0" ]] ; then
-		commit_status="$(echo `svn status`)"
-		if [[ "$commit_status" =~ '\.ebuild' ]] ; then
+		if [[ "$(svn status)" =~ '\.ebuild' ]] ; then
 			ebegin "Running repoman"
 			export PORTDIR_OVERLAY="$(dirname $(dirname $(pwd)))"
 			repoman
@@ -118,16 +125,33 @@ svn_up() {
 			pushd .. >/dev/null
 			(( num_new_dirs++ ))
 		done
+
 		ebegin "Updating working copy to latest version from repository"
+
 		if [[ "$opt_verbose" == "1" ]] ; then
 			svn update || set $?  
 		else
 			svn update -q || set $?
 		fi
+
 		eend ${1:-0}
+
 		for (( i=num_new_dirs ; i > 0 ; i-- )) ; do
 	   		popd >/dev/null
 		done
+
+		local conflict_files=$(svn status | sed -rn 's/^C.+ ([^ ]+)$/\1/p')
+		if [[ -n "$conflict_files" ]] ; then
+			echo "!!! Error: Some local files have changes that conflict with the latest"
+			echo "!!! revisions in the repository. Please contact their committer(s) to resolve"
+			echo "!!! the conflicts manually before running sunrise-commit again:"
+			for filename in $conflict_files ; do
+				echo "!!!"
+				echo "!!!        file: ${filename}"
+				echo "!!!   committer: $(svn info ${filename} | sed -rn 's/Last Changed Author\: (.*)$/\1/p')"
+			done
+			exit 1
+		fi
 	fi
 	return ${1:-0}
 }
