Reviewed up to revision 473
git-svn-id: http://overlays.gentoo.org/svn/proj/sunrise@474 12608f7e-a915-0410-b2f3-ce240db1b126

diff --git a/reviewed/scripts/sunrise-commit b/reviewed/scripts/sunrise-commit
--- a/reviewed/scripts/sunrise-commit
+++ b/reviewed/scripts/sunrise-commit
@@ -14,7 +14,6 @@ YELLOW=$WARN
 
 commit_category="$(echo `pwd` | awk -F/ '{ print $(NF-1) }')"
 commit_package="$(echo `pwd` | awk -F/ '{ print $NF }')"
-commit_status="$(echo `svn status`)"
 num_new_dirs=0
 opt_changelog=0
 opt_noformat=0
@@ -52,7 +51,7 @@ create_digests() {
 
 repoman_check() {
 	if [[ "$opt_norepoman" == "0" ]] ; then
-		if [[ "$(svn status)" =~ '\.ebuild' ]] ; then
+		if [[ "$(echo `svn status`)" =~ '\.ebuild' ]] ; then
 			ebegin "Running repoman"
 			export PORTDIR_OVERLAY="$(dirname $(dirname $(pwd)))"
 			repoman
@@ -65,9 +64,9 @@ repoman_check() {
 svn_add() {
 	ebegin "Adding local changes to working copy"
 	if [[ "$opt_verbose" == "1" ]] ; then
-		svn add * --force
+		svn add ../$(basename `pwd`) --force
 	else
-		svn add * --force -q
+		svn add ../$(basename `pwd`) --force -q
 	fi
 	eend $?
 }
@@ -80,7 +79,7 @@ svn_commit() {
 	done
 
 	if [[ "$opt_noformat" == "0" ]] ; then
-		commit_status="$(echo `svn status`)"
+		local commit_status="$(echo `svn status`)"
 		if [[ "$commit_status" =~ '\.ebuild' ]] ; then
 			commit_message="${commit_category}/${commit_package}: ${commit_message}"
 		else
@@ -143,8 +142,8 @@ svn_up() {
 		local conflict_files=$(svn status | sed -rn 's/^C.+ ([^ ]+)$/\1/p')
 		if [[ -n "$conflict_files" ]] ; then
 			echo "!!! Error: Some local files have changes that conflict with the latest"
-			echo "!!! revisions in the repository. Please contact their committer(s) to resolve"
-			echo "!!! the conflicts manually before running sunrise-commit again:"
+			echo "!!! revisions in the repository. Please contact the previous committer(s) to"
+			echo "!!! resolve the conflicts manually before running sunrise-commit again:"
 			for filename in $conflict_files ; do
 				echo "!!!"
 				echo "!!!        file: ${filename}"
@@ -226,15 +225,16 @@ if [[ -z "$*" ]] ; then
 	exit 1
 fi
 
-if [[ -z "$commit_status" ]] ; then
-	ewarn "No changes found in current directory tree."
-	exit 1
-fi
-
 svn_up || exit $?
 [[ ! -e metadata.xml ]] && cp ../../skel.metadata.xml metadata.xml >/dev/null 2>&1
 changelog_append "$*" || exit $?
 create_digests || exit $?
 svn_add || exit $?
+
+if [[ -z "$(svn status)" ]] ; then
+	echo "!!! Error: No changes found in current directory tree. Aborting commit."
+	exit 1
+fi
+
 repoman_check || exit $?
 svn_commit "$*" || exit $?
